### ISSUE TITLE
`X is on list L` tests only check the first xpath result

### ISSUE THREAD

**Issue by andylolz** [pwyf/foxpath-tools#2]
[`activity.xpath(xpath)`](https://github.com/pwyf/foxpath-tools/blob/5a52a789/foxpath/mapping.py#L135) may return multiple results. For instance, activities may have many `<sector>` tags, and we probably want to check all of those sector codes are on the [Sector codelist](http://iatistandard.org/201/codelists/SectorVocabulary/).

Currently, [only the first xpath result is checked](https://github.com/pwyf/foxpath-tools/blob/5a52a789/foxpath/mapping.py#L136-L145).

**Comment by markbrough** [comment]
Just FYI, this was originally deliberate and could presumably lead to some significant changes in scores

**Comment by andylolz** [comment]
> Just FYI, this was originally deliberate

Ah! Why? To make it run faster?

> could presumably lead to some significant changes in scores

It’s possible, yes… Scores would only go down, though. To mitigate this, we could (fix and) use `at least one X is on list L`.

**Comment by markbrough** [comment]
> Ah! Why? To make it run faster?

No I don't think it would make much difference to performance. The reason was that foxpath essentially returns `TRUE` or `FALSE` results, so you either have to be strict or lax in terms of how you handle multiple results. E.g. if you have 5 sectors and one of them is not using a code on the codelist, then should the organisation fail the test for that activity? Maybe, but that might be a little punitive? We previously generally erred on the side of generosity (though doesn't necessarily mean that it should remain that way).

**Comment by andylolz** [comment]
> We previously generally erred on the side of generosity (though doesn't necessarily mean that it should remain that way).

So `X is on list L` previously did something like “the first X is on list L”. I don’t think the first encountered X should get special treatment, so I think this is wrong.

I’ve changed it so it does something more like `all X are on list L`. It might be preferable to instead add `at least one X is on list L` and use that instead.

I’m basically just aiming to make the foxpath expressions a bit more self-explanatory.

**Comment by andylolz** [comment]
Okay – in 7f0289f7 I’ve tried to be a bit more explicit that we are checking “at least one”. I’ve also added `every X is on list L` in case that becomes useful.

Ideally, I think the tests should explicitly state “*at least one* X is on list L” and the default should be “every” (since that seems more of a natural way to understand it) but for backward compatibility I’ve done the opposite.

**Comment by andylolz** [comment]
I’ve swapped this around again, so we’re using “at least one X is on list L”. That’s because I’m not sure how to handle conjunctions and empty lists. Consider these two tests:

1. x exists or y exists
2. at least one x is on list L or at least one y is on list L

2 is a stricter test than 1, in the sense that all activities that pass 2 will necessarily pass 1.

3. every x is on list L and every y is on list L

Depending on how this is implemented, 3 may not be a stricter test than 1 (if neither x nor y exist, I’d expect 3 to pass.) If ‘every …’ instead expects its input to exist and we use ‘or’ instead of ‘and’, passing activities *would* be a subset of those that pass 1… But using ‘every … *or* every …’ is really weird, and making ‘every’ implicitly insist on existence is also weird.

For now, let’s use ‘at least one … or at least one …’. This sort of change is more appropriate for the github consultation, anyway.
